### ISSUE TITLE
Hide Service Role API key and have reveal button

### ISSUE THREAD

**Issue by calendee** [supabase/ui#99] opened 2021-01-25 09:25 UTC
# Feature request

## Is your feature request related to a problem? Please describe.

On a projects Settings -> API view, it's pretty easy to accidentally copy the "service_role" API key instead of the "public" one despite the "secret" label.

## Describe the solution you'd like

It'd be great if the "service_role" API key were obscurbed with "***" be default. Then, add a "Reveal" button to allow the user to see/copy it.

![supabase-api-keys](https://user-images.githubusercontent.com/57374/105686508-3ab3f900-5eef-11eb-9561-51055439b3ed.png)

**Comment by MildTomato** [comment] 2021-01-25 09:34
Hi @calendee - thanks for the suggestion! I think this would be a great addition 🙌

this is somewhat of a duplicate of #96, which covers copy and reveal actions, so I'm going to close this one in favour of continuing the thread over there.

**Closed by MildTomato** 2021-01-25 09:34 UTC
Labels: enhancement
