### ISSUE TITLE
useEffect doesn't work on user after signIn

### ISSUE THREAD

**Issue by benjaminpreiss** [supabase/ui#335] opened 2022-03-18 23:14 UTC
# Bug report

## Describe the bug

useEffect doesn't work on user after signIn.

## To Reproduce

Here is my Login page from nextjs:

```js
import { Auth } from "@supabase/ui";
import { createClient } from "@supabase/supabase-js";
import { useRouter } from 'next/router'
import { useEffect } from 'react'

export default function Login({}) {
    const { user } = Auth.useUser();
	const supabase = createClient(
		"**********",
		"***********"
	);
    const router = useRouter()
    useEffect(() => {
        if (user) {
            if (window.history.length > 1 && document.referrer.indexOf(window.location.host) !== -1) {
                router.back();
              } else {
                router.push("/");
              }
        }
      }, [user])

    return (
        <>
            <Auth providers={['facebook', 'github']} supabaseClient={supabase}/>
        </>
    )
}
```

## Expected behavior

After I sign in, the user should be redirected to another page. Instead, nothing happens (not even a rerender.

**Comment by julienR2** [comment] 2022-07-06 14:00
I have the same issue, while using `supabaseClient` from `@supabase/auth-helpers-nextjs` 🤔

I correctly setup the `UserProvider` in `_app`, but the `user` value return by useUser (from `@supabase/auth-helpers-react`) stays null.
And setting up the "redirectTo" params  on `Auth` doesn't change a think either..

Any ideas ?

**Comment by julienR2** [comment] 2022-07-06 14:05
I guess my question might be a bit different from the op.. @benjaminpreiss did you make sur you setup the `Auth.UserContextProvider` in a parent component ?

On my side it's more of a question about how to make `@supabase/auth-helpers-nextjs` work correctly with `@supabase/ui`, since we are supposed to setup two different context for each (respectively `UserProvider` and `Auth.UserContextProvider`)..

**Comment by egor-romanov** [comment] 2024-01-19 11:26
Closing the issue, as it seems like the original issue has been partially resolved or there is a working solution. I'd prefer someone to create a new issue with a fresh description if it's still an issue.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen it.
Cheers!

I tried to reproduce using [the following project](https://github.com/supabase-community/supabase-graphql-example). But it works as expected (if you add `[router, user]` to `useEffect` in `app/pages/login.tsx`)

**Closed by egor-romanov** 2024-01-19 11:26 UTC
Labels: bug
